Repository allanpaiz/JETA, pull requests merged in 2025-03, with the labels that each got.

#57 Added SongLibraryMode scene
  json/users.json
  src/main/java/com/tuneup/SongLibraryMode.java
  src/main/java/com/tuneup/TuneUp.java
  src/main/java/com/tuneup/TuneUpUI.java
  target/classes/com/tuneup/CreateMode.class
  target/classes/com/tuneup/DataLoader$1.class
  target/classes/com/tuneup/DataLoader$2.class
  target/classes/com/tuneup/DataLoader.class
  target/classes/com/tuneup/DataWriter.class
  target/classes/com/tuneup/ExperienceLevel.class
  target/classes/com/tuneup/FileUtils.class
  target/classes/com/tuneup/InstrumentFactory.class
  target/classes/com/tuneup/InstrumentType.class
  target/classes/com/tuneup/Lesson.class
  target/classes/com/tuneup/LessonMode.class
  target/classes/com/tuneup/PasswordUtils.class
  target/classes/com/tuneup/PianoStrategy.class
  target/classes/com/tuneup/PlayMode.class
  target/classes/com/tuneup/ProfileManager.class
  target/classes/com/tuneup/Progress.class
  target/classes/com/tuneup/Song.class
  target/classes/com/tuneup/SongDetails.class
  target/classes/com/tuneup/SongLibrary.class
  target/classes/com/tuneup/SongLibraryMode.class
  target/classes/com/tuneup/TuneUp.class
  target/classes/com/tuneup/TuneUpUI.class
  target/classes/com/tuneup/User.class
  target/classes/com/tuneup/UserProfile$1.class
  target/classes/com/tuneup/UserProfile.class
  target/classes/com/tuneup/UserType.class
  target/classes/module-info.class
Labels: enhancement

#60 Cleaning up Development & Code
  .gitignore
  .vscode/settings.json
  README.md
  json/users.json
  pom.xml
  src/main/java/com/module-info.java
  src/main/java/com/tuneup/SongLibraryMode.java
  src/main/java/com/tuneup/TuneUp.java
  src/main/java/com/tuneup/TuneUpUI.java
  target/classes/com/tuneup/CreateMode.class
  target/classes/com/tuneup/DataConstants.class
  target/classes/com/tuneup/DataLoader$1.class
  target/classes/com/tuneup/DataLoader$2.class
  target/classes/com/tuneup/DataLoader.class
  target/classes/com/tuneup/DataWriter.class
  target/classes/com/tuneup/ExperienceLevel.class
  target/classes/com/tuneup/FileUtils.class
  target/classes/com/tuneup/InstrumentFactory.class
  target/classes/com/tuneup/InstrumentStrategy.class
  target/classes/com/tuneup/InstrumentType.class
  target/classes/com/tuneup/Lesson.class
  target/classes/com/tuneup/LessonMode.class
  target/classes/com/tuneup/Mode.class
  target/classes/com/tuneup/PasswordUtils.class
  target/classes/com/tuneup/PianoStrategy.class
  target/classes/com/tuneup/PlayMode.class
  target/classes/com/tuneup/ProfileManager.class
  target/classes/com/tuneup/Progress.class
  target/classes/com/tuneup/Song.class
  target/classes/com/tuneup/SongDetails.class
  target/classes/com/tuneup/SongLibrary.class
  target/classes/com/tuneup/SongLibraryMode.class
  target/classes/com/tuneup/TuneUp.class
  target/classes/com/tuneup/TuneUpUI.class
  target/classes/com/tuneup/User.class
  target/classes/com/tuneup/UserProfile$1.class
  target/classes/com/tuneup/UserProfile.class
  target/classes/com/tuneup/UserType.class
  target/classes/module-info.class
  target/maven-archiver/pom.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/tuneup-1.0-SNAPSHOT.jar
Labels: bug

#70 Development
  json/songs.json
  src/main/java/com/tuneup/CreateMode.java
  src/main/java/com/tuneup/DataConstants.java
  src/main/java/com/tuneup/DataLoader.java
  src/main/java/com/tuneup/DataWriter.java
  src/main/java/com/tuneup/Song.java
  src/main/java/com/tuneup/SongLibrary.java
  src/main/java/com/tuneup/SongLibraryMode.java
Labels: enhancement

#71 Updating Lessons.java
  json/lessons.json
  src/main/java/com/tuneup/Lesson.java
  src/main/java/com/tuneup/SongDetails.java
  src/main/java/com/tuneup/User.java
Labels: documentation

#84 Updating Branch
  json/songs.json
  json/users.json
  src/main/java/com/tuneup/CreateMode.java
  src/main/java/com/tuneup/PasswordUtils.java
  src/main/java/com/tuneup/ProfileManager.java
  src/main/java/com/tuneup/Song.java
  src/main/java/com/tuneup/TerminalUI.java
  src/main/java/com/tuneup/TuneUp.java
  src/main/java/com/tuneup/User.java
  src/main/java/com/tuneup/UserProfile.java
Labels: documentation

#87 Profile Manager & UML Class Diagram
  docs/UML_class_diagram.pdf
  json/users.json
  src/main/java/com/tuneup/Lesson.java
  src/main/java/com/tuneup/ProfileManager.java
  src/main/java/com/tuneup/User.java
Labels: documentation, enhancement

#90 Updating Branch & Merging with Changes
  json/users.json
  src/main/java/com/tuneup/CreateMode.java
  src/main/java/com/tuneup/FileUtils.java
  src/main/java/com/tuneup/ProfileManager.java
  src/main/java/com/tuneup/TerminalUI.java
  src/main/java/com/tuneup/TuneUp.java
  src/main/java/com/tuneup/User.java
Labels: documentation, enhancement

#91 Updating Branch
  json/lessons.json
  src/main/java/com/tuneup/LessonLibrary.java
Labels: documentation

#107 Search by Artist Name
  src/main/java/com/tuneup/SongLibraryMode.java
Labels: enhancement

#111 Assigned JavaDoc
  src/main/java/com/tuneup/InstrumentFactory.java
  src/main/java/com/tuneup/PianoStrategy.java
  src/main/java/com/tuneup/SongLibrary.java
  src/main/java/com/tuneup/User.java
Labels: documentation

#118 Adding Fred User to Branch
  json/users.json
Labels: refactor

#122 Updaing doc names
  docs/UML_class_diagram.pdf
  docs/requirements.pdf
  docs/sequence1.pdf
  docs/sequence2.pdf
  docs/uml-class-diagram.pdf
  json/songs.json
Labels: documentation
